update 221027
ymuichiro/decentrized-guild pull request #21
Opened 2022-10-27 14:01 UTC by karriz-dev

+ add prettier 
+ add `react-router-dom`
+ add `polyfill` (for symbol-sdk)
+ add SSS Extension Login

@ymuichiro 

今日のPRは今後の作業方向を合わせていく最初のスタート地点になればと思います。
もしコードで理解できない部分、あるいは直さなければならない部分があればおっしゃってください。

2022-10-27 14:05 UTC, karriz-dev commented
あ、そしてブランチの名前はですね。

frontend/add-feature_name
frontend/fix-fix_name

このようにfrontend作業ということを明示します。
symbol公式repositoryで使う方法ですが良さそうですね。

2022-10-27 14:17 UTC, ymuichiro commented on frontend/src/store/user/UserAtom.ts
> +export interface UserInformation {
@karriz-dev 

`User` や `Quest` といった interface は `frontend/src/@types/swagger.ts` に自動的に出力されるようにしました。以下のコマンドを実行すると更新されます。今回の PR はこのまま進めて、使えそうであれば自動出力されたものに置き換えてより効率的に進めたいと思います。

https://github.com/ymuichiro/decentralized-guild/blob/11aebfac5367b2ab5f086093429308feb1ae5303/package.json#L6

2022-10-27 14:23 UTC, ymuichiro commented on frontend/src/pages/login/Join.tsx
> +const ROLE_CARD_DATA: RoleModel[] = [
@karriz-dev 
このページは消してもいいかもしれません。認識が違う所がありそうです。
Worker も Quest を募集することは出来て良いと思うので、Worker か Requester かは状況に応じて変わります。
Guild owner も参加時に即なれるロールではない為、このページはスキップして良いと思います。

2022-10-27 14:27 UTC, ymuichiro requested changes
少しコメントを追記しました。

2022-10-28 01:46 UTC, karriz-dev commented on frontend/src/store/user/UserAtom.ts
> +export interface UserInformation {
はい、確認しました。 次の作業から適用します！

2022-10-28 01:50 UTC, karriz-dev commented on frontend/src/pages/login/Join.tsx
> +const ROLE_CARD_DATA: RoleModel[] = [
1人が様々な役割を果たすことができることを考えます。

該当ページは削除してすぐに情報入力画面を表示し、Dashboardに移動して自分の職業タイプを多重に見られる形で構成する必要があります。

2022-10-28 01:52 UTC, karriz-dev commented
すべて確認完了しました。 Approveしたらmergeを進めます。

2022-10-28 01:52 UTC, karriz-dev commented
@ymuichiro  すべて確認完了しました。 Approveしたらmergeを進めます。

2022-10-28 02:26 UTC, ymuichiro approved these changes

2022-10-28 02:26 UTC, ymuichiro commented
@karriz-dev 承認しました！

2022-10-28 07:55 UTC, merged